### ISSUE TITLE
Region Selection plots

### ISSUE THREAD

**Issue by gschwend** [linea-it/ic-cluster#1]
Como parte das atividades da Iniciação Científica, criar um Jupyter notebook para a caracterização da etapa de seleção de regiões no pipeline VAC Cluster. Para concluir este issue, o notebook deverá conter (marcar checkboxes conforme o progresso):

- [x]  Visualização dos systematic maps.
    - [x] Detection Fraction (cada linha da tabela é um pixel, para griz bands).
    - [x] N-images 
- [x]  Visualização dos depth mapas (por bandas (griz), e por SN (5,10)).
    - [x] Mapas de magnitudes (Permitem selecionar o pixel com problema, e não somente algum objeto nele). 
    - [x] Mapas com SN.
    - [x] Como otimizar o código de extração de sub-tabela?
- [x]  Visualização da foreground objects mask (código bitmap, descrição no gold catalog)
    - Remove diversos objetos (estrelas, aglomerados globulares, galáxias anãs próximas) e a área próxima a eles.
- [x]  Visualização do footprint map (é 0 ou 1 )
    - É o mapa resultante a partir dos cortes feitos nos mapas anteriores.
- [x]  Cálculo da área efetiva (depende dos cortes feitos)
     - Cada pixel tem que ter area ponderada pelo detection fraction (somatório dos detection fractions). 

Usando datashadder (ser interativo, inclusive os valores de densidade):
- [x]  Distribuição espacial dos objetos (mapa de densidades)
- [ ]  Distribuição espacial do redshift médio/mediano
- [ ]  Distribuição espacial do erro no redshift (erro médio)

**Comment by gschwend** [comment]
@gabrieloliveira2428 os notebooks do DP0 estão públicos em https://github.com/fklich/rubin-dp0
Aquele que eu comentei é o "08b".

**Comment by gabzitcho** [comment]
Certo!

Em qua., 12 de jan. de 2022 11:58, Julia Gschwend ***@***.***>
escreveu:
