### ISSUE TITLE
Object Selection plots

### ISSUE THREAD

**Issue by gschwend** [linea-it/ic-cluster#2]
Como parte das atividades da Iniciação Científica, criar um Jupyter notebook para a caracterização da etapa de seleção de objetos no pipeline VAC Cluster. Para concluir este issue, o notebook deverá conter (marcar checkboxes conforme o progresso):

- [x]  Distribuições de magnitudes
- [x]  Distribuições de magnitude errors
- [x]  Distribuições de cores
- [x]  Distribuições de photo-z
- [x]  Distribuições de photo-z error
- [x]  Number counts normalizados com referências da literatura (vide product log)
- [x]  Plot magnitude X error
- [x]  Plot magnitude X redshift
- [x]  Color-magnitude diagrams
- [x]  Color-color diagrams

**Comment by AndressaWille** [comment]
Coloquei um rascunho de alguns plots no meu branch. Eu só não sei porque os histogramas estão brancos mesmo que eu tenha definido a cor como azul... E deve ter mais algumas coisas para arrumar.
